<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://toulemarket.com/retour_pvit_process',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS =>'<REPONSE><INTERFACEID>BAKOAI</INTERFACEID> <REF>AA</REF><TYPE>1</TYPE> <STATUT>0</STATUT><OPERATEUR>AM</OPERATEUR><TEL_CLIENT>0777</TEL_CLIENT>
<TOKEN>lllll</TOKEN><AGENT>A</AGENT><MESSAGE>Bonjour MAZOU</MESSAGE><NUM_TRANSACTION>kkk</NUM_TRANSACTION> </REPONSE>',
  CURLOPT_HTTPHEADER => array(
    'Content-Type: text/xml',
    'Cookie: PHPSESSID=05l96mekffq2brq71ppbpimcus; XSRF-TOKEN=eyJpdiI6Ildpd2ZaNVVNbzFRVWFqTjRXWXNiZEE9PSIsInZhbHVlIjoiTXd6K3JZNWVla24yTmUvWS9xNUJnUW1RUCtGdmFkbEFLTWFseGJXcjliWUhsZDR1NjA2UUtySXRzUDdyTHJXVDM0YVZiOEZSOXpUNnFaR1BnYXFWeDVhaWhkNzRCeGg1and3c1VrOVpvWlZnL2ZraU1VajZhaVhISnFrZzFNVjAiLCJtYWMiOiJiOGRiMTI1ZTZkM2NjOGFkZjVjODc4YTdhZGEwY2M3Y2FlMmQ3ZmM4NzJhM2I3N2E2ZjljMjEwNzYwNTI0MmM1IiwidGFnIjoiIn0%3D; toule_market_session=eyJpdiI6ImNPdzNYclhFSjJrOFY5aHdHdTM1cUE9PSIsInZhbHVlIjoiRVBLUmhVR2VzWlFHQ1NpQVdXSk9GY29ISjR1N0dCWlhKTThiNTBrM2RyaWM1cnJwWTlpd0UzUUVGSVZwTk9RNGVyZ3NTdldRQ2ZRc0FzUDVNc2ZPTGsxWmNqdXZaQnFYN0QxTXBuUHh4K1o2MVVYYkFCN0ZyRDQzeGN0ZFdvajMiLCJtYWMiOiJiOTc1MDNmMWIyNDQ2ZTRiODY1ZDNlNzNjM2U3OThiMDBmNTQ3ZWExYTI4OWE1ZDEzMDY0MGQ2YjNhZjNjMWJkIiwidGFnIjoiIn0%3D'
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;